apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-prod-deploy
    labels:
      app: nginx-app-prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: gautham1999/project:v1
          ports:
          - containerPort: 8080
